apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nevz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nevz
    app.kubernetes.io/part-of: byoc-app-kyrq
  name: nevz
spec:
  rules:
  - host: nevz-byoc-teyu-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-6zc8g.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: nevz
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
